def log_exception(exception: Exception):
    print(str(exception))
